language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_script:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script:
    - nosetests --with-coverage tests/test-utils.py
#  - 'nosetests tests/test-listall.py'
#  - 'nosetests tests/test-rulesgenerator.py'
#  - 'nosetests tests/test-utils.py'
#  - '[ "${TRAVIS_SECURE_ENV_VARS}" = "true" ] && nosetests tests/test-utils_sns.py || false'
    - nosetests --with-coverage tests/test-rules-ruleset.py
    - nosetests --with-coverage tests/test-rules-processingengine.py
    - nosetests --with-coverage --nocapture tests/test-scout2.py

# use container-base infrastructure
sudo: false

# Update test coverage -- only when run locally
#after_success:
#    - coveralls
